---

services:
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyS3curePass!
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports: ["9200:9200","9600:9600"]
    volumes:
      - os_data:/usr/share/opensearch/data
    networks: [logs-net]
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    ports: ["5601:5601"]
    volumes:
      - os_dash_data:/usr/share/opensearch-dashboards/data
    networks: [logs-net]
    restart: unless-stopped

volumes:
  os_data:
  os_dash_data:

networks:
  logs-net:
    driver: bridge
