---

services:
  questionnaire:
    build:
      context: .
    container_name: questionnaire
    ports:
      - "8081:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4000/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      q-net:
        ipv4_address: 172.21.0.40

networks:
  q-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24